package mx.unam.is.modelo;
// Generated 20/02/2018 02:50:15 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Serializable nombre;
     private Serializable oficinas;
     private Serializable fundacion;
     private Integer numeroEmpleados;
     private Serializable contacto;
     private Serializable presidente;
     private Set teners = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(Serializable nombre) {
        this.nombre = nombre;
    }
    public Empresa(Serializable nombre, Serializable oficinas, Serializable fundacion, Integer numeroEmpleados, Serializable contacto, Serializable presidente, Set teners) {
       this.nombre = nombre;
       this.oficinas = oficinas;
       this.fundacion = fundacion;
       this.numeroEmpleados = numeroEmpleados;
       this.contacto = contacto;
       this.presidente = presidente;
       this.teners = teners;
    }
   
    public Serializable getNombre() {
        return this.nombre;
    }
    
    public void setNombre(Serializable nombre) {
        this.nombre = nombre;
    }
    public Serializable getOficinas() {
        return this.oficinas;
    }
    
    public void setOficinas(Serializable oficinas) {
        this.oficinas = oficinas;
    }
    public Serializable getFundacion() {
        return this.fundacion;
    }
    
    public void setFundacion(Serializable fundacion) {
        this.fundacion = fundacion;
    }
    public Integer getNumeroEmpleados() {
        return this.numeroEmpleados;
    }
    
    public void setNumeroEmpleados(Integer numeroEmpleados) {
        this.numeroEmpleados = numeroEmpleados;
    }
    public Serializable getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Serializable contacto) {
        this.contacto = contacto;
    }
    public Serializable getPresidente() {
        return this.presidente;
    }
    
    public void setPresidente(Serializable presidente) {
        this.presidente = presidente;
    }
    public Set getTeners() {
        return this.teners;
    }
    
    public void setTeners(Set teners) {
        this.teners = teners;
    }




}


