package mx.unam.is.modelo;
// Generated 20/02/2018 02:50:15 PM by Hibernate Tools 4.3.1



/**
 * Postular generated by hbm2java
 */
public class Postular  implements java.io.Serializable {


     private PostularId id;
     private Profesionista profesionista;
     private Vacante vacante;

    public Postular() {
    }

    public Postular(PostularId id, Profesionista profesionista, Vacante vacante) {
       this.id = id;
       this.profesionista = profesionista;
       this.vacante = vacante;
    }
   
    public PostularId getId() {
        return this.id;
    }
    
    public void setId(PostularId id) {
        this.id = id;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }
    public Vacante getVacante() {
        return this.vacante;
    }
    
    public void setVacante(Vacante vacante) {
        this.vacante = vacante;
    }




}


