package mx.unam.is.modelo;
// Generated 20/02/2018 02:50:15 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Profesionista generated by hbm2java
 */
public class Profesionista  implements java.io.Serializable {


     private Serializable nombre;
     private Serializable correo;
     private Serializable telefono;
     private Serializable contrasena;
     private Serializable nacionalidad;
     private Serializable carrera;
     private Serializable skilsNombre;
     private Serializable skilsGrado;
     private Serializable faColegio;
     private Serializable faGrado;
     private Serializable faPeriodo;
     private Serializable explaPeriodo;
     private Serializable explaCargo;
     private Serializable explaEmpresa;
     private Set postulars = new HashSet(0);

    public Profesionista() {
    }

	
    public Profesionista(Serializable nombre) {
        this.nombre = nombre;
    }
    public Profesionista(Serializable nombre, Serializable correo, Serializable telefono, Serializable contrasena, Serializable nacionalidad, Serializable carrera, Serializable skilsNombre, Serializable skilsGrado, Serializable faColegio, Serializable faGrado, Serializable faPeriodo, Serializable explaPeriodo, Serializable explaCargo, Serializable explaEmpresa, Set postulars) {
       this.nombre = nombre;
       this.correo = correo;
       this.telefono = telefono;
       this.contrasena = contrasena;
       this.nacionalidad = nacionalidad;
       this.carrera = carrera;
       this.skilsNombre = skilsNombre;
       this.skilsGrado = skilsGrado;
       this.faColegio = faColegio;
       this.faGrado = faGrado;
       this.faPeriodo = faPeriodo;
       this.explaPeriodo = explaPeriodo;
       this.explaCargo = explaCargo;
       this.explaEmpresa = explaEmpresa;
       this.postulars = postulars;
    }
   
    public Serializable getNombre() {
        return this.nombre;
    }
    
    public void setNombre(Serializable nombre) {
        this.nombre = nombre;
    }
    public Serializable getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(Serializable correo) {
        this.correo = correo;
    }
    public Serializable getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Serializable telefono) {
        this.telefono = telefono;
    }
    public Serializable getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(Serializable contrasena) {
        this.contrasena = contrasena;
    }
    public Serializable getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(Serializable nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public Serializable getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Serializable carrera) {
        this.carrera = carrera;
    }
    public Serializable getSkilsNombre() {
        return this.skilsNombre;
    }
    
    public void setSkilsNombre(Serializable skilsNombre) {
        this.skilsNombre = skilsNombre;
    }
    public Serializable getSkilsGrado() {
        return this.skilsGrado;
    }
    
    public void setSkilsGrado(Serializable skilsGrado) {
        this.skilsGrado = skilsGrado;
    }
    public Serializable getFaColegio() {
        return this.faColegio;
    }
    
    public void setFaColegio(Serializable faColegio) {
        this.faColegio = faColegio;
    }
    public Serializable getFaGrado() {
        return this.faGrado;
    }
    
    public void setFaGrado(Serializable faGrado) {
        this.faGrado = faGrado;
    }
    public Serializable getFaPeriodo() {
        return this.faPeriodo;
    }
    
    public void setFaPeriodo(Serializable faPeriodo) {
        this.faPeriodo = faPeriodo;
    }
    public Serializable getExplaPeriodo() {
        return this.explaPeriodo;
    }
    
    public void setExplaPeriodo(Serializable explaPeriodo) {
        this.explaPeriodo = explaPeriodo;
    }
    public Serializable getExplaCargo() {
        return this.explaCargo;
    }
    
    public void setExplaCargo(Serializable explaCargo) {
        this.explaCargo = explaCargo;
    }
    public Serializable getExplaEmpresa() {
        return this.explaEmpresa;
    }
    
    public void setExplaEmpresa(Serializable explaEmpresa) {
        this.explaEmpresa = explaEmpresa;
    }
    public Set getPostulars() {
        return this.postulars;
    }
    
    public void setPostulars(Set postulars) {
        this.postulars = postulars;
    }




}


