package mx.unam.is.modelo;
// Generated 20/02/2018 02:50:15 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Arrays;

/**
 * TenerId generated by hbm2java
 */
public class TenerId  implements java.io.Serializable {


     private byte[] nombre;
     private Serializable puesto;

    public TenerId() {
    }

    public TenerId(byte[] nombre, Serializable puesto) {
       this.nombre = nombre;
       this.puesto = puesto;
    }
   
    public byte[] getNombre() {
        return this.nombre;
    }
    
    public void setNombre(byte[] nombre) {
        this.nombre = nombre;
    }
    public Serializable getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Serializable puesto) {
        this.puesto = puesto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TenerId) ) return false;
		 TenerId castOther = ( TenerId ) other; 
         
		 return ( (this.getNombre()==castOther.getNombre()) || ( this.getNombre()!=null && castOther.getNombre()!=null && Arrays.equals(this.getNombre(), castOther.getNombre()) ) )
 && ( (this.getPuesto()==castOther.getPuesto()) || ( this.getPuesto()!=null && castOther.getPuesto()!=null && this.getPuesto().equals(castOther.getPuesto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         int nombreHashcode = 0;
         byte[] nombreProperty = this.getNombre();
         if(nombreProperty != null) {
             nombreHashcode = 1;
             for (int i=0; i<nombreProperty.length; i++) {
                 nombreHashcode = 37 * nombreHashcode + nombreProperty[i];
             }
         }

         result = 37 * result + nombreHashcode;

         result = 37 * result + ( getPuesto() == null ? 0 : this.getPuesto().hashCode() );
         return result;
   }   


}


