package mx.unam.is.modelo;
// Generated 20/02/2018 02:50:15 PM by Hibernate Tools 4.3.1



/**
 * Tener generated by hbm2java
 */
public class Tener  implements java.io.Serializable {


     private TenerId id;
     private Empresa empresa;
     private Vacante vacante;

    public Tener() {
    }

    public Tener(TenerId id, Empresa empresa, Vacante vacante) {
       this.id = id;
       this.empresa = empresa;
       this.vacante = vacante;
    }
   
    public TenerId getId() {
        return this.id;
    }
    
    public void setId(TenerId id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Vacante getVacante() {
        return this.vacante;
    }
    
    public void setVacante(Vacante vacante) {
        this.vacante = vacante;
    }




}


