package mx.unam.is.modelo;
// Generated 20/02/2018 02:50:15 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Vacante generated by hbm2java
 */
public class Vacante  implements java.io.Serializable {


     private Serializable puesto;
     private Serializable actividades;
     private Serializable descripcion;
     private Serializable salario;
     private Serializable lugar;
     private Serializable horario;
     private Set postulars = new HashSet(0);
     private Set teners = new HashSet(0);

    public Vacante() {
    }

	
    public Vacante(Serializable puesto) {
        this.puesto = puesto;
    }
    public Vacante(Serializable puesto, Serializable actividades, Serializable descripcion, Serializable salario, Serializable lugar, Serializable horario, Set postulars, Set teners) {
       this.puesto = puesto;
       this.actividades = actividades;
       this.descripcion = descripcion;
       this.salario = salario;
       this.lugar = lugar;
       this.horario = horario;
       this.postulars = postulars;
       this.teners = teners;
    }
   
    public Serializable getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Serializable puesto) {
        this.puesto = puesto;
    }
    public Serializable getActividades() {
        return this.actividades;
    }
    
    public void setActividades(Serializable actividades) {
        this.actividades = actividades;
    }
    public Serializable getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(Serializable descripcion) {
        this.descripcion = descripcion;
    }
    public Serializable getSalario() {
        return this.salario;
    }
    
    public void setSalario(Serializable salario) {
        this.salario = salario;
    }
    public Serializable getLugar() {
        return this.lugar;
    }
    
    public void setLugar(Serializable lugar) {
        this.lugar = lugar;
    }
    public Serializable getHorario() {
        return this.horario;
    }
    
    public void setHorario(Serializable horario) {
        this.horario = horario;
    }
    public Set getPostulars() {
        return this.postulars;
    }
    
    public void setPostulars(Set postulars) {
        this.postulars = postulars;
    }
    public Set getTeners() {
        return this.teners;
    }
    
    public void setTeners(Set teners) {
        this.teners = teners;
    }




}


